# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4671d70a5c747b907f02e007a22cbd2b"
name = "insurance"
handle = "insurance-11"
application_url = "https://sunshine-boy.click/auth"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = false
scopes = "read_orders,read_all_orders,write_orders,read_script_tags,write_script_tags,read_shipping,read_products,read_customers,read_themes,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,write_fulfillments"


[build]
dev_store_url = "insurance-t1.myshopify.com"

[auth]
redirect_urls = [
  "https://sunshine-boy.click/auth",
  "https://api.sunshine-boy.click/api/webhook/install"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "https://api.sunshine-boy.click/api/webhook/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://api.sunshine-boy.click/api/webhook/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://api.sunshine-boy.click/api/webhook/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
