# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4671d70a5c747b907f02e007a22cbd2b"
name = "insurance"
handle = "insurance-11"
application_url = "https://s.sunshine-boy.click/"
embedded = true

[app_preferences]
url = "https://s.sunshine-boy.click"

[build]
dev_store_url = "test-shop2-xx.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = false
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_publications,read_publications,write_files,write_themes"

[auth]
redirect_urls = [
  "https://s.sunshine-boy.click/insurance/auth",
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = [
  "orders/updated",
  "orders/delete",
  "app_subscriptions/update",
  "app_subscriptions/approaching_capped_amount",
  "app/uninstalled",
  "products/update",
  "products/delete",
  "shop/update"
]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://api.sunshine-boy.click/insurance/api/v1/webhook/customer-redact"

[pos]
embedded = false
